test

diff --git a/.github/workflows/github-actions-demo.yml b/.github/workflows/github-actions-demo.yml
--- a/.github/workflows/github-actions-demo.yml
+++ b/.github/workflows/github-actions-demo.yml
@@ -7,14 +7,14 @@ jobs:
     steps:
       - run: "echo Jobs: ${{ github.job }}"
       - uses: actions/checkout@v3
-      - run: "ls /tmp/tototata"
+      - run: "ls /tmp/tototata" || echo "STATUS=failed" >> "$GITHUB_OUTPUT"
+        id: status
         continue-on-error: true
       - name: The job has failed
         if: ${{ failure() }}
         run: "echo FAILED"
-      - name: Set color
-        id: color-generator
-        run: echo "SELECTED_COLOR=green" >> "$GITHUB_OUTPUT"
+      - name: The job has failed
+        run: echo "echo Status: ${{ steps.status.outputs.STATUS }}"
 
   job_2:
     runs-on: [self-hosted, linux]
